# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ryan Walls
tagline:             '@ryanwalls'
description:         'A site to help future me solve problems that I have already solved.'
url:                 http://ryanwalls.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ryan Walls
  url:               https://twitter.com/ryanwalls
  email:             ryanscottwalls@gmail.com

# Custom vars
version:             1.0.0

kramdown:
  input: GFM
  hard_wrap: false
